export const seoMetadata = {
  LeadScout: {
    title: "LeadScout - Advanced Lead Discovery for Seller-Financed Mortgage Notes",
    description: "LeadScout empowers professionals to discover, analyze, and enrich leads for seller-financed mortgage notes with cutting-edge tools for lead generation, data mining, enrichment, and skip tracing.",
    keywords: "advanced lead generation, data mining tools, lead enrichment, skip tracing software, seller-financed mortgage notes, mortgage lead discovery",
    structuredData: {
      "@context": "https://schema.org",
      "@type": "SoftwareApplication",
      name: "LeadScout",
      description: "Empower professionals to discover and enrich leads for seller-financed mortgage notes with advanced tools.",
      applicationCategory: "BusinessApplication",
      keywords: "advanced lead generation, data mining tools, lead enrichment, skip tracing software",
    },
  },
  EngagementManager: {
    title: "EngagementManager - Optimize Lead Communication Across Channels",
    description: "EngagementManager simplifies multi-channel communication with leads using direct mail, SMS, and campaign management tools, while providing engagement analytics and customizable white-label forms.",
    keywords: "multi-channel communication, direct mail campaigns, SMS marketing, engagement analytics, white-label forms, lead communication tools",
    structuredData: {
      "@context": "https://schema.org",
      "@type": "SoftwareApplication",
      name: "EngagementManager",
      description: "Simplify and optimize communication with leads across multiple channels using advanced tools.",
      applicationCategory: "BusinessApplication",
      keywords: "multi-channel communication, direct mail campaigns, SMS marketing, engagement analytics",
    },
  },
  DealTracker: {
    title: "DealTracker - Comprehensive Deal Lifecycle Management",
    description: "DealTracker offers robust tools for tracking deals through their lifecycle, including deal pipeline visualization, progress monitoring, task management, and detailed reporting.",
    keywords: "deal lifecycle management, pipeline tracking, progress monitoring tools, task management software, deal reporting solutions",
    structuredData: {
      "@context": "https://schema.org",
      "@type": "SoftwareApplication",
      name: "DealTracker",
      description: "Track and manage deals comprehensively through their lifecycle with advanced tools and reporting.",
      applicationCategory: "BusinessApplication",
      keywords: "deal lifecycle management, pipeline tracking, progress monitoring tools",
    },
  },
  TradeMerchant: {
    title: "TradeMerchant - Streamlined Trading for Mortgage Notes",
    description: "TradeMerchant facilitates seamless buying and selling of mortgage notes with features like trade execution, in-depth market analysis, transaction management, and secure deal exchange.",
    keywords: "mortgage note trading, trade execution tools, market analysis software, transaction management, secure deal exchange",
    structuredData: {
      "@context": "https://schema.org",
      "@type": "SoftwareApplication",
      name: "TradeMerchant",
      description: "Facilitate seamless trading of mortgage notes with advanced tools for execution and management.",
      applicationCategory: "BusinessApplication",
      keywords: "mortgage note trading, trade execution tools, market analysis software",
    },
  },
  FundingAssistance: {
    title: "Funding Assistance - Tailored Solutions for Deal Financing",
    description: "Funding Assistance connects you with tailored funding solutions, offering application support, access to capital networks, and expert financial planning for successful deal financing.",
    keywords: "deal financing solutions, funding application support, capital network access, financial planning services, tailored funding",
    structuredData: {
      "@context": "https://schema.org",
      "@type": "SoftwareApplication",
      name: "Funding Assistance",
      description: "Connect with tailored funding solutions and expert financial planning for successful deal financing.",
      applicationCategory: "BusinessApplication",
      keywords: "deal financing solutions, funding application support, capital network access",
    },
  },
  NoteSleuth: {
    title: "NoteSleuth - Advanced Due Diligence for Mortgage Notes",
    description: "NoteSleuth ensures the accuracy and viability of deals or leads with comprehensive due diligence, document verification, risk assessment, and compliance checks for mortgage notes.",
    keywords: "advanced due diligence, document verification tools, risk assessment software, compliance checks, mortgage note accuracy",
    structuredData: {
      "@context": "https://schema.org",
      "@type": "SoftwareApplication",
      name: "NoteSleuth",
      description: "Ensure the accuracy and viability of deals or leads with advanced due diligence and compliance tools.",
      applicationCategory: "BusinessApplication",
      keywords: "advanced due diligence, document verification tools, risk assessment software",
    },
  },
};
